name: Generate Awesome Contentful Readme

on:
  schedule:
    # daily
    - cron: "0 0 * * *"
  push:

jobs:
  build:
    name: Generate project listings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-project-listing
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
